const travel = [
    {
        "id_post": 411485,
        "name": "Tour du lịch Nhật Bản 5 ngày 5 đêm - Khám phá xứ sở mặt trời mọc",
        "url": "https://www.vietnambooking.com/du-lich/tour-du-lich-nhat-ban-5-ngay-5-dem.html",
        "category": "tour_internation",
        "price": "35639000",
        "image": "https://www.vietnambooking.com/wp-content/uploads/2023/05/tour-du-lich-nhat-ban-5-ngay-5-dem-1-150x150.jpg",
        "type": "item",
        "location": "Hồ Chí Minh",
        "slug": "ho-chi-minh",
        "code": "TOHCMNHB5N5D-MBGR-411485"
    },
    {
        "id_post": 111358,
        "name": "Tour du lịch Đà Nẵng mùa hè 3 ngày 2 đêm",
        "url": "https://www.vietnambooking.com/du-lich/tour-mua-he-da-nang-3-ngay-2-dem.html",
        "category": "tour_domestic",
        "price": "3590000",
        "image": "https://www.vietnambooking.com/wp-content/uploads/2018/06/tour-mua-he-da-nang-3-ngay-2-dem-150x150.png",
        "type": "item",
        "location": "Đà Nẵng",
        "slug": "da-nang",
        "code": "TODANHOAMTR3N2D-XEHE-111358"
    },
    {
        "id_post": 408696,
        "name": "Đặt ngay tour lễ 2/9 giá rẻ với ưu đãi cực sốc!",
        "url": "https://www.vietnambooking.com/du-lich/tour-du-lich/tour-le-2-9.html",
        "category": "tour_domestic",
        "price": "1000000",
        "image": "https://www.vietnambooking.com/wp-content/uploads/2023/05/tour-le-2-9-12-150x150.png",
        "type": "item",
        "location": "Hồ Chí Minh",
        "slug": "ho-chi-minh",
        "code": "TOHCMTN--408696"
    },
    {
        "id_post": 407034,
        "name": "Tour Đồng bằng sông Cửu Long 4N3Đ: Hành trình khám phá 8 tỉnh miền Tây",
        "url": "https://www.vietnambooking.com/du-lich/tour-dong-bang-song-cuu-long.html",
        "category": "tour_domestic",
        "price": "4290000",
        "image": "https://www.vietnambooking.com/wp-content/uploads/2023/04/tour-dong-bang-song-cuu-long-10-2023-150x150.png",
        "type": "item",
        "location": "Hồ Chí Minh",
        "slug": "ho-chi-minh",
        "code": "TOHCMCATMTA4N3D-XEDL-407034"
    },
    {
        "id_post": 406903,
        "name": "Tour Đà Nẵng - Bà Nà - Hội An - Ngũ Hành Sơn từ Hà Nội 3N2Đ cực HOT",
        "url": "https://www.vietnambooking.com/du-lich/tour-da-nang-ba-na-hoi-an-ngu-hanh-son-tu-ha-noi.html",
        "category": "tour_domestic",
        "price": "6990000",
        "image": "https://www.vietnambooking.com/wp-content/uploads/2023/03/Tour-da-nang-ba-na-hoi-an-ngu-hanh-son-tu-ha-noi-2-2023-150x150.jpg",
        "type": "item",
        "location": "Hồ Chí Minh",
        "slug": "ho-chi-minh",
        "code": "TOHCMDAN3N2D-MBDLHE-406903"
    },
    {
        "id_post": 406794,
        "name": "Tour Đà Nẵng - Bà Nà - Hội An - Ngũ Hành Sơn từ TP.HCM | Giá Cực SHOCK",
        "url": "https://www.vietnambooking.com/du-lich/tour-da-nang-ba-na-hoi-an-ngu-hanh-son-tu-tphcm.html",
        "category": "tour_domestic",
        "price": "6290000",
        "image": "https://www.vietnambooking.com/wp-content/uploads/2023/03/Tour-da-nang-ba-na-hoi-an-ngu-hanh-son-tu-tphcm-2023-150x150.png",
        "type": "item",
        "location": "Hồ Chí Minh",
        "slug": "ho-chi-minh",
        "code": "TOHCMDAN3N2D-MBDL-406794"
    },
    {
        "id_post": 181430,
        "name": "Tour du lịch Hà Tiên - Phú Quốc 3 ngày 3 đêm | Khám phá Đảo Ngọc từ TP HCM",
        "url": "https://www.vietnambooking.com/du-lich/tour-du-lich-tp-hcm-ha-tien-phu-quoc-3n3d.html",
        "category": "tour_domestic",
        "price": "3986000",
        "image": "https://www.vietnambooking.com/wp-content/uploads/2023/03/ha-tien-phu-quoc-3n3d-2023-150x150.png",
        "type": "item",
        "location": "Hồ Chí Minh",
        "slug": "ho-chi-minh",
        "code": "TOHCMKIGMNAPHQ3N3D-TTHE-181430"
    },
    {
        "id_post": 70458,
        "name": "Tour Nha Trang - Đà Lạt 4 ngày 3 đêm: Khám phá thành phố biển đến xứ ngàn hoa",
        "url": "https://www.vietnambooking.com/du-lich/tour-nha-trang-da-lat-4n3d.html",
        "category": "tour_domestic",
        "price": "4290000",
        "image": "https://www.vietnambooking.com/wp-content/uploads/2023/03/tour-du-lich-nha-trang-da-lat-2023-150x150.png",
        "type": "item",
        "location": "Nha Trang",
        "slug": "nha-trang",
        "code": "TONHTDAL4N3D-XETLHE-70458"
    },
    {
        "id_post": 239864,
        "name": "Tour du lịch Đà Lạt Nha Trang 5 ngày 4 đêm từ Hà Nội | Cao nguyên đại ngàn & Biển xanh vẫy gọi",
        "url": "https://www.vietnambooking.com/du-lich/tour-ha-noi-nha-trang-da-lat-5n4d.html",
        "category": "tour_domestic",
        "price": "8990000",
        "image": "https://www.vietnambooking.com/wp-content/uploads/2023/03/ha-noi-da-lat-nha-trang-5-ngay-4-dem-1-2023-150x150.png",
        "type": "item",
        "location": "Hà Nội",
        "slug": "ha-noi",
        "code": "TOHANDALNHT5N4D-TTMBHE-239864"
    },
    {
        "id_post": 374368,
        "name": "Tour Đà Lạt 3 ngày 3 đêm l Lạc vào chốn tiên cảnh giữa nhân gian",
        "url": "https://www.vietnambooking.com/du-lich/tour-da-lat-3-ngay-3-dem.html",
        "category": "tour_domestic",
        "price": "2390000",
        "image": "https://www.vietnambooking.com/wp-content/uploads/2023/03/tour-da-lat-3-ngay-3-dem-1-2023-150x150.jpg",
        "type": "item",
        "location": "Hồ Chí Minh",
        "slug": "ho-chi-minh",
        "code": "VNBHCMDAL3N3D-XETG-374368"
    },
    {
        "id_post": 94787,
        "name": "Tour du lịch Đà Lạt 3 ngày 2 đêm | Thưởng ngoạn miền Cao Nguyên mộng mơ",
        "url": "https://www.vietnambooking.com/du-lich/tour-da-lat-3-ngay-2-dem.html",
        "category": "tour_domestic",
        "price": "5090000",
        "image": "https://www.vietnambooking.com/wp-content/uploads/2023/03/tour-da-lat-3-ngay-2-dem-2023.jpg-150x150.png",
        "type": "item",
        "location": "Hà Nội",
        "slug": "ha-noi",
        "code": "TOHANDAL3N2D-MBHE-94787"
    },
    {
        "id_post": 404796,
        "name": "Tour Miền Tây 1 ngày Vietnambooking | Chương trình khám phá miệt vườn dân dã, bình dị",
        "url": "https://www.vietnambooking.com/du-lich/tour-mien-tay-1-ngay-vietnambooking.html",
        "category": "tour_domestic",
        "price": "699000",
        "image": "https://www.vietnambooking.com/wp-content/uploads/2023/03/tour-mien-tay-1-ngay-vietnambooking-2023-150x150.png",
        "type": "item",
        "location": "Hồ Chí Minh",
        "slug": "ho-chi-minh",
        "code": "VNBHCMMTATN-TT-404796"
    },
    {
        "id_post": 71462,
        "name": "Tour Hà Tiên - Phú Quốc 3N3Đ 30/04: Grand World Phú Quốc - Công viên nước Hòn Thơm",
        "url": "https://www.vietnambooking.com/du-lich/tour-du-lich-30-04-thien-duong-ruc-nang-phu-quoc-3n3d.html",
        "category": "tour_domestic",
        "price": "4586000",
        "image": "https://www.vietnambooking.com/wp-content/uploads/2023/03/tour-ha-tien-phu-quoc-3n3d-1-150x150.png",
        "type": "item",
        "location": "Hồ Chí Minh",
        "slug": "ho-chi-minh",
        "code": "TOHCMKIGMNAPHQ3N3D-TTLH-71462"
    },
    {
        "id_post": 103616,
        "name": "Tour du lịch Đà Nẵng Lễ 30/4 4N3Đ | Bà Nà Hills - Hội An - Huế - Quảng Bình |Thứ 5 hàng tuần",
        "url": "https://www.vietnambooking.com/du-lich/tour-da-nang-le-30-4-le-hoi-phao-hoa.html",
        "category": "tour_domestic",
        "price": "7790000",
        "image": "https://www.vietnambooking.com/wp-content/uploads/2022/03/tour-da-nang-le-30-4-le-hoi-phao-hoa-1-150x150.png",
        "type": "item",
        "location": "Hồ Chí Minh",
        "slug": "ho-chi-minh",
        "code": "TOHCMDANHOAHUE4N3D-MBLH-103616"
    },
]


module.exports = {travel}